//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolucionSoap.Cliente.MVC.ServicioComprobanteProducto {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComprobanteProductoModelo", Namespace="http://schemas.datacontract.org/2004/07/SolucionSoap.Servidor.WCF.Modelo")]
    [System.SerializableAttribute()]
    public partial class ComprobanteProductoModelo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadComprobanteProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdentificadorComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdentificadorComprobanteProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreComprobanteProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioComprobanteProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalComprobanteProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadComprobanteProducto {
            get {
                return this.CantidadComprobanteProductoField;
            }
            set {
                if ((this.CantidadComprobanteProductoField.Equals(value) != true)) {
                    this.CantidadComprobanteProductoField = value;
                    this.RaisePropertyChanged("CantidadComprobanteProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdentificadorComprobante {
            get {
                return this.IdentificadorComprobanteField;
            }
            set {
                if ((this.IdentificadorComprobanteField.Equals(value) != true)) {
                    this.IdentificadorComprobanteField = value;
                    this.RaisePropertyChanged("IdentificadorComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdentificadorComprobanteProducto {
            get {
                return this.IdentificadorComprobanteProductoField;
            }
            set {
                if ((this.IdentificadorComprobanteProductoField.Equals(value) != true)) {
                    this.IdentificadorComprobanteProductoField = value;
                    this.RaisePropertyChanged("IdentificadorComprobanteProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreComprobanteProducto {
            get {
                return this.NombreComprobanteProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreComprobanteProductoField, value) != true)) {
                    this.NombreComprobanteProductoField = value;
                    this.RaisePropertyChanged("NombreComprobanteProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecioComprobanteProducto {
            get {
                return this.PrecioComprobanteProductoField;
            }
            set {
                if ((this.PrecioComprobanteProductoField.Equals(value) != true)) {
                    this.PrecioComprobanteProductoField = value;
                    this.RaisePropertyChanged("PrecioComprobanteProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalComprobanteProducto {
            get {
                return this.TotalComprobanteProductoField;
            }
            set {
                if ((this.TotalComprobanteProductoField.Equals(value) != true)) {
                    this.TotalComprobanteProductoField = value;
                    this.RaisePropertyChanged("TotalComprobanteProducto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRespuestaModelo", Namespace="http://schemas.datacontract.org/2004/07/SolucionSoap.Servidor.WCF.Modelo")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ActualizarRespuestaModelo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.EliminarRespuestaModelo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ObtenerRespuestaModeloOfComprobanteProductoModeloKTVAo3T5))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ListarRespuestaModeloOfComprobanteProductoModeloKTVAo3T5))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.RegistrarRespuestaModelo))]
    public partial class BaseRespuestaModelo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeRespuestaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ErrorRespuesta {
            get {
                return this.ErrorRespuestaField;
            }
            set {
                if ((this.ErrorRespuestaField.Equals(value) != true)) {
                    this.ErrorRespuestaField = value;
                    this.RaisePropertyChanged("ErrorRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeRespuesta {
            get {
                return this.MensajeRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeRespuestaField, value) != true)) {
                    this.MensajeRespuestaField = value;
                    this.RaisePropertyChanged("MensajeRespuesta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActualizarRespuestaModelo", Namespace="http://schemas.datacontract.org/2004/07/SolucionSoap.Servidor.WCF.Modelo")]
    [System.SerializableAttribute()]
    public partial class ActualizarRespuestaModelo : SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.BaseRespuestaModelo {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EliminarRespuestaModelo", Namespace="http://schemas.datacontract.org/2004/07/SolucionSoap.Servidor.WCF.Modelo")]
    [System.SerializableAttribute()]
    public partial class EliminarRespuestaModelo : SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.BaseRespuestaModelo {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObtenerRespuestaModeloOfComprobanteProductoModeloKTVAo3T5", Namespace="http://schemas.datacontract.org/2004/07/SolucionSoap.Servidor.WCF.Modelo")]
    [System.SerializableAttribute()]
    public partial class ObtenerRespuestaModeloOfComprobanteProductoModeloKTVAo3T5 : SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.BaseRespuestaModelo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ComprobanteProductoModelo ModeloRespuestaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ComprobanteProductoModelo ModeloRespuesta {
            get {
                return this.ModeloRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloRespuestaField, value) != true)) {
                    this.ModeloRespuestaField = value;
                    this.RaisePropertyChanged("ModeloRespuesta");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListarRespuestaModeloOfComprobanteProductoModeloKTVAo3T5", Namespace="http://schemas.datacontract.org/2004/07/SolucionSoap.Servidor.WCF.Modelo")]
    [System.SerializableAttribute()]
    public partial class ListarRespuestaModeloOfComprobanteProductoModeloKTVAo3T5 : SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.BaseRespuestaModelo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ComprobanteProductoModelo[] ListaRespuestaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ComprobanteProductoModelo[] ListaRespuesta {
            get {
                return this.ListaRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaRespuestaField, value) != true)) {
                    this.ListaRespuestaField = value;
                    this.RaisePropertyChanged("ListaRespuesta");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistrarRespuestaModelo", Namespace="http://schemas.datacontract.org/2004/07/SolucionSoap.Servidor.WCF.Modelo")]
    [System.SerializableAttribute()]
    public partial class RegistrarRespuestaModelo : SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.BaseRespuestaModelo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdentificadorRespuestaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdentificadorRespuesta {
            get {
                return this.IdentificadorRespuestaField;
            }
            set {
                if ((this.IdentificadorRespuestaField.Equals(value) != true)) {
                    this.IdentificadorRespuestaField = value;
                    this.RaisePropertyChanged("IdentificadorRespuesta");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioComprobanteProducto.IComprobanteProductoRepositorio")]
    public interface IComprobanteProductoRepositorio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobanteProductoRepositorio/Registrar", ReplyAction="http://tempuri.org/IComprobanteProductoRepositorio/RegistrarResponse")]
        SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.RegistrarRespuestaModelo Registrar(SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ComprobanteProductoModelo comprobanteProductoModelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobanteProductoRepositorio/Registrar", ReplyAction="http://tempuri.org/IComprobanteProductoRepositorio/RegistrarResponse")]
        System.Threading.Tasks.Task<SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.RegistrarRespuestaModelo> RegistrarAsync(SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ComprobanteProductoModelo comprobanteProductoModelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobanteProductoRepositorio/Actualizar", ReplyAction="http://tempuri.org/IComprobanteProductoRepositorio/ActualizarResponse")]
        SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ActualizarRespuestaModelo Actualizar(SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ComprobanteProductoModelo comprobanteProductoModelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobanteProductoRepositorio/Actualizar", ReplyAction="http://tempuri.org/IComprobanteProductoRepositorio/ActualizarResponse")]
        System.Threading.Tasks.Task<SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ActualizarRespuestaModelo> ActualizarAsync(SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ComprobanteProductoModelo comprobanteProductoModelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobanteProductoRepositorio/Eliminar", ReplyAction="http://tempuri.org/IComprobanteProductoRepositorio/EliminarResponse")]
        SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.EliminarRespuestaModelo Eliminar(int IdentificadorComprobanteProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobanteProductoRepositorio/Eliminar", ReplyAction="http://tempuri.org/IComprobanteProductoRepositorio/EliminarResponse")]
        System.Threading.Tasks.Task<SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.EliminarRespuestaModelo> EliminarAsync(int IdentificadorComprobanteProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobanteProductoRepositorio/Obtener", ReplyAction="http://tempuri.org/IComprobanteProductoRepositorio/ObtenerResponse")]
        SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ObtenerRespuestaModeloOfComprobanteProductoModeloKTVAo3T5 Obtener(int IdentificadorComprobanteProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobanteProductoRepositorio/Obtener", ReplyAction="http://tempuri.org/IComprobanteProductoRepositorio/ObtenerResponse")]
        System.Threading.Tasks.Task<SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ObtenerRespuestaModeloOfComprobanteProductoModeloKTVAo3T5> ObtenerAsync(int IdentificadorComprobanteProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobanteProductoRepositorio/ListarPorIdentificadorComproba" +
            "nte", ReplyAction="http://tempuri.org/IComprobanteProductoRepositorio/ListarPorIdentificadorComproba" +
            "nteResponse")]
        SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ListarRespuestaModeloOfComprobanteProductoModeloKTVAo3T5 ListarPorIdentificadorComprobante(int IdentificadorComprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobanteProductoRepositorio/ListarPorIdentificadorComproba" +
            "nte", ReplyAction="http://tempuri.org/IComprobanteProductoRepositorio/ListarPorIdentificadorComproba" +
            "nteResponse")]
        System.Threading.Tasks.Task<SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ListarRespuestaModeloOfComprobanteProductoModeloKTVAo3T5> ListarPorIdentificadorComprobanteAsync(int IdentificadorComprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobanteProductoRepositorio/Listar", ReplyAction="http://tempuri.org/IComprobanteProductoRepositorio/ListarResponse")]
        SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ListarRespuestaModeloOfComprobanteProductoModeloKTVAo3T5 Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobanteProductoRepositorio/Listar", ReplyAction="http://tempuri.org/IComprobanteProductoRepositorio/ListarResponse")]
        System.Threading.Tasks.Task<SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ListarRespuestaModeloOfComprobanteProductoModeloKTVAo3T5> ListarAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IComprobanteProductoRepositorioChannel : SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.IComprobanteProductoRepositorio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComprobanteProductoRepositorioClient : System.ServiceModel.ClientBase<SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.IComprobanteProductoRepositorio>, SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.IComprobanteProductoRepositorio {
        
        public ComprobanteProductoRepositorioClient() {
        }
        
        public ComprobanteProductoRepositorioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComprobanteProductoRepositorioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComprobanteProductoRepositorioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComprobanteProductoRepositorioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.RegistrarRespuestaModelo Registrar(SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ComprobanteProductoModelo comprobanteProductoModelo) {
            return base.Channel.Registrar(comprobanteProductoModelo);
        }
        
        public System.Threading.Tasks.Task<SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.RegistrarRespuestaModelo> RegistrarAsync(SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ComprobanteProductoModelo comprobanteProductoModelo) {
            return base.Channel.RegistrarAsync(comprobanteProductoModelo);
        }
        
        public SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ActualizarRespuestaModelo Actualizar(SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ComprobanteProductoModelo comprobanteProductoModelo) {
            return base.Channel.Actualizar(comprobanteProductoModelo);
        }
        
        public System.Threading.Tasks.Task<SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ActualizarRespuestaModelo> ActualizarAsync(SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ComprobanteProductoModelo comprobanteProductoModelo) {
            return base.Channel.ActualizarAsync(comprobanteProductoModelo);
        }
        
        public SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.EliminarRespuestaModelo Eliminar(int IdentificadorComprobanteProducto) {
            return base.Channel.Eliminar(IdentificadorComprobanteProducto);
        }
        
        public System.Threading.Tasks.Task<SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.EliminarRespuestaModelo> EliminarAsync(int IdentificadorComprobanteProducto) {
            return base.Channel.EliminarAsync(IdentificadorComprobanteProducto);
        }
        
        public SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ObtenerRespuestaModeloOfComprobanteProductoModeloKTVAo3T5 Obtener(int IdentificadorComprobanteProducto) {
            return base.Channel.Obtener(IdentificadorComprobanteProducto);
        }
        
        public System.Threading.Tasks.Task<SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ObtenerRespuestaModeloOfComprobanteProductoModeloKTVAo3T5> ObtenerAsync(int IdentificadorComprobanteProducto) {
            return base.Channel.ObtenerAsync(IdentificadorComprobanteProducto);
        }
        
        public SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ListarRespuestaModeloOfComprobanteProductoModeloKTVAo3T5 ListarPorIdentificadorComprobante(int IdentificadorComprobante) {
            return base.Channel.ListarPorIdentificadorComprobante(IdentificadorComprobante);
        }
        
        public System.Threading.Tasks.Task<SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ListarRespuestaModeloOfComprobanteProductoModeloKTVAo3T5> ListarPorIdentificadorComprobanteAsync(int IdentificadorComprobante) {
            return base.Channel.ListarPorIdentificadorComprobanteAsync(IdentificadorComprobante);
        }
        
        public SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ListarRespuestaModeloOfComprobanteProductoModeloKTVAo3T5 Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<SolucionSoap.Cliente.MVC.ServicioComprobanteProducto.ListarRespuestaModeloOfComprobanteProductoModeloKTVAo3T5> ListarAsync() {
            return base.Channel.ListarAsync();
        }
    }
}
