//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolucionSoap.Cliente.MVC.ServicioComprobante {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComprobanteModelo", Namespace="http://schemas.datacontract.org/2004/07/SolucionSoap.Servidor.WCF.Modelo")]
    [System.SerializableAttribute()]
    public partial class ComprobanteModelo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClienteComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DescuentoComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdentificadorComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ImpuestoComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SubTotalComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VendedorComprobanteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClienteComprobante {
            get {
                return this.ClienteComprobanteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteComprobanteField, value) != true)) {
                    this.ClienteComprobanteField = value;
                    this.RaisePropertyChanged("ClienteComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DescuentoComprobante {
            get {
                return this.DescuentoComprobanteField;
            }
            set {
                if ((this.DescuentoComprobanteField.Equals(value) != true)) {
                    this.DescuentoComprobanteField = value;
                    this.RaisePropertyChanged("DescuentoComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaComprobante {
            get {
                return this.FechaComprobanteField;
            }
            set {
                if ((this.FechaComprobanteField.Equals(value) != true)) {
                    this.FechaComprobanteField = value;
                    this.RaisePropertyChanged("FechaComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdentificadorComprobante {
            get {
                return this.IdentificadorComprobanteField;
            }
            set {
                if ((this.IdentificadorComprobanteField.Equals(value) != true)) {
                    this.IdentificadorComprobanteField = value;
                    this.RaisePropertyChanged("IdentificadorComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ImpuestoComprobante {
            get {
                return this.ImpuestoComprobanteField;
            }
            set {
                if ((this.ImpuestoComprobanteField.Equals(value) != true)) {
                    this.ImpuestoComprobanteField = value;
                    this.RaisePropertyChanged("ImpuestoComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SubTotalComprobante {
            get {
                return this.SubTotalComprobanteField;
            }
            set {
                if ((this.SubTotalComprobanteField.Equals(value) != true)) {
                    this.SubTotalComprobanteField = value;
                    this.RaisePropertyChanged("SubTotalComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoComprobante {
            get {
                return this.TipoComprobanteField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoComprobanteField, value) != true)) {
                    this.TipoComprobanteField = value;
                    this.RaisePropertyChanged("TipoComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalComprobante {
            get {
                return this.TotalComprobanteField;
            }
            set {
                if ((this.TotalComprobanteField.Equals(value) != true)) {
                    this.TotalComprobanteField = value;
                    this.RaisePropertyChanged("TotalComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VendedorComprobante {
            get {
                return this.VendedorComprobanteField;
            }
            set {
                if ((object.ReferenceEquals(this.VendedorComprobanteField, value) != true)) {
                    this.VendedorComprobanteField = value;
                    this.RaisePropertyChanged("VendedorComprobante");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRespuestaModelo", Namespace="http://schemas.datacontract.org/2004/07/SolucionSoap.Servidor.WCF.Modelo")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SolucionSoap.Cliente.MVC.ServicioComprobante.ActualizarRespuestaModelo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SolucionSoap.Cliente.MVC.ServicioComprobante.EliminarRespuestaModelo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SolucionSoap.Cliente.MVC.ServicioComprobante.ObtenerRespuestaModeloOfComprobanteModeloKTVAo3T5))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SolucionSoap.Cliente.MVC.ServicioComprobante.ListarRespuestaModeloOfComprobanteModeloKTVAo3T5))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SolucionSoap.Cliente.MVC.ServicioComprobante.RegistrarRespuestaModelo))]
    public partial class BaseRespuestaModelo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeRespuestaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ErrorRespuesta {
            get {
                return this.ErrorRespuestaField;
            }
            set {
                if ((this.ErrorRespuestaField.Equals(value) != true)) {
                    this.ErrorRespuestaField = value;
                    this.RaisePropertyChanged("ErrorRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeRespuesta {
            get {
                return this.MensajeRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeRespuestaField, value) != true)) {
                    this.MensajeRespuestaField = value;
                    this.RaisePropertyChanged("MensajeRespuesta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActualizarRespuestaModelo", Namespace="http://schemas.datacontract.org/2004/07/SolucionSoap.Servidor.WCF.Modelo")]
    [System.SerializableAttribute()]
    public partial class ActualizarRespuestaModelo : SolucionSoap.Cliente.MVC.ServicioComprobante.BaseRespuestaModelo {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EliminarRespuestaModelo", Namespace="http://schemas.datacontract.org/2004/07/SolucionSoap.Servidor.WCF.Modelo")]
    [System.SerializableAttribute()]
    public partial class EliminarRespuestaModelo : SolucionSoap.Cliente.MVC.ServicioComprobante.BaseRespuestaModelo {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObtenerRespuestaModeloOfComprobanteModeloKTVAo3T5", Namespace="http://schemas.datacontract.org/2004/07/SolucionSoap.Servidor.WCF.Modelo")]
    [System.SerializableAttribute()]
    public partial class ObtenerRespuestaModeloOfComprobanteModeloKTVAo3T5 : SolucionSoap.Cliente.MVC.ServicioComprobante.BaseRespuestaModelo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SolucionSoap.Cliente.MVC.ServicioComprobante.ComprobanteModelo ModeloRespuestaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SolucionSoap.Cliente.MVC.ServicioComprobante.ComprobanteModelo ModeloRespuesta {
            get {
                return this.ModeloRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloRespuestaField, value) != true)) {
                    this.ModeloRespuestaField = value;
                    this.RaisePropertyChanged("ModeloRespuesta");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListarRespuestaModeloOfComprobanteModeloKTVAo3T5", Namespace="http://schemas.datacontract.org/2004/07/SolucionSoap.Servidor.WCF.Modelo")]
    [System.SerializableAttribute()]
    public partial class ListarRespuestaModeloOfComprobanteModeloKTVAo3T5 : SolucionSoap.Cliente.MVC.ServicioComprobante.BaseRespuestaModelo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SolucionSoap.Cliente.MVC.ServicioComprobante.ComprobanteModelo[] ListaRespuestaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SolucionSoap.Cliente.MVC.ServicioComprobante.ComprobanteModelo[] ListaRespuesta {
            get {
                return this.ListaRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaRespuestaField, value) != true)) {
                    this.ListaRespuestaField = value;
                    this.RaisePropertyChanged("ListaRespuesta");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistrarRespuestaModelo", Namespace="http://schemas.datacontract.org/2004/07/SolucionSoap.Servidor.WCF.Modelo")]
    [System.SerializableAttribute()]
    public partial class RegistrarRespuestaModelo : SolucionSoap.Cliente.MVC.ServicioComprobante.BaseRespuestaModelo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdentificadorRespuestaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdentificadorRespuesta {
            get {
                return this.IdentificadorRespuestaField;
            }
            set {
                if ((this.IdentificadorRespuestaField.Equals(value) != true)) {
                    this.IdentificadorRespuestaField = value;
                    this.RaisePropertyChanged("IdentificadorRespuesta");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioComprobante.IComprobanteRepositorio")]
    public interface IComprobanteRepositorio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobanteRepositorio/Registrar", ReplyAction="http://tempuri.org/IComprobanteRepositorio/RegistrarResponse")]
        SolucionSoap.Cliente.MVC.ServicioComprobante.RegistrarRespuestaModelo Registrar(SolucionSoap.Cliente.MVC.ServicioComprobante.ComprobanteModelo comprobanteModelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobanteRepositorio/Registrar", ReplyAction="http://tempuri.org/IComprobanteRepositorio/RegistrarResponse")]
        System.Threading.Tasks.Task<SolucionSoap.Cliente.MVC.ServicioComprobante.RegistrarRespuestaModelo> RegistrarAsync(SolucionSoap.Cliente.MVC.ServicioComprobante.ComprobanteModelo comprobanteModelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobanteRepositorio/Actualizar", ReplyAction="http://tempuri.org/IComprobanteRepositorio/ActualizarResponse")]
        SolucionSoap.Cliente.MVC.ServicioComprobante.ActualizarRespuestaModelo Actualizar(SolucionSoap.Cliente.MVC.ServicioComprobante.ComprobanteModelo comprobanteModelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobanteRepositorio/Actualizar", ReplyAction="http://tempuri.org/IComprobanteRepositorio/ActualizarResponse")]
        System.Threading.Tasks.Task<SolucionSoap.Cliente.MVC.ServicioComprobante.ActualizarRespuestaModelo> ActualizarAsync(SolucionSoap.Cliente.MVC.ServicioComprobante.ComprobanteModelo comprobanteModelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobanteRepositorio/Eliminar", ReplyAction="http://tempuri.org/IComprobanteRepositorio/EliminarResponse")]
        SolucionSoap.Cliente.MVC.ServicioComprobante.EliminarRespuestaModelo Eliminar(int IdentificadorComprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobanteRepositorio/Eliminar", ReplyAction="http://tempuri.org/IComprobanteRepositorio/EliminarResponse")]
        System.Threading.Tasks.Task<SolucionSoap.Cliente.MVC.ServicioComprobante.EliminarRespuestaModelo> EliminarAsync(int IdentificadorComprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobanteRepositorio/Obtener", ReplyAction="http://tempuri.org/IComprobanteRepositorio/ObtenerResponse")]
        SolucionSoap.Cliente.MVC.ServicioComprobante.ObtenerRespuestaModeloOfComprobanteModeloKTVAo3T5 Obtener(int IdentificadorComprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobanteRepositorio/Obtener", ReplyAction="http://tempuri.org/IComprobanteRepositorio/ObtenerResponse")]
        System.Threading.Tasks.Task<SolucionSoap.Cliente.MVC.ServicioComprobante.ObtenerRespuestaModeloOfComprobanteModeloKTVAo3T5> ObtenerAsync(int IdentificadorComprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobanteRepositorio/Listar", ReplyAction="http://tempuri.org/IComprobanteRepositorio/ListarResponse")]
        SolucionSoap.Cliente.MVC.ServicioComprobante.ListarRespuestaModeloOfComprobanteModeloKTVAo3T5 Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComprobanteRepositorio/Listar", ReplyAction="http://tempuri.org/IComprobanteRepositorio/ListarResponse")]
        System.Threading.Tasks.Task<SolucionSoap.Cliente.MVC.ServicioComprobante.ListarRespuestaModeloOfComprobanteModeloKTVAo3T5> ListarAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IComprobanteRepositorioChannel : SolucionSoap.Cliente.MVC.ServicioComprobante.IComprobanteRepositorio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComprobanteRepositorioClient : System.ServiceModel.ClientBase<SolucionSoap.Cliente.MVC.ServicioComprobante.IComprobanteRepositorio>, SolucionSoap.Cliente.MVC.ServicioComprobante.IComprobanteRepositorio {
        
        public ComprobanteRepositorioClient() {
        }
        
        public ComprobanteRepositorioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComprobanteRepositorioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComprobanteRepositorioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComprobanteRepositorioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SolucionSoap.Cliente.MVC.ServicioComprobante.RegistrarRespuestaModelo Registrar(SolucionSoap.Cliente.MVC.ServicioComprobante.ComprobanteModelo comprobanteModelo) {
            return base.Channel.Registrar(comprobanteModelo);
        }
        
        public System.Threading.Tasks.Task<SolucionSoap.Cliente.MVC.ServicioComprobante.RegistrarRespuestaModelo> RegistrarAsync(SolucionSoap.Cliente.MVC.ServicioComprobante.ComprobanteModelo comprobanteModelo) {
            return base.Channel.RegistrarAsync(comprobanteModelo);
        }
        
        public SolucionSoap.Cliente.MVC.ServicioComprobante.ActualizarRespuestaModelo Actualizar(SolucionSoap.Cliente.MVC.ServicioComprobante.ComprobanteModelo comprobanteModelo) {
            return base.Channel.Actualizar(comprobanteModelo);
        }
        
        public System.Threading.Tasks.Task<SolucionSoap.Cliente.MVC.ServicioComprobante.ActualizarRespuestaModelo> ActualizarAsync(SolucionSoap.Cliente.MVC.ServicioComprobante.ComprobanteModelo comprobanteModelo) {
            return base.Channel.ActualizarAsync(comprobanteModelo);
        }
        
        public SolucionSoap.Cliente.MVC.ServicioComprobante.EliminarRespuestaModelo Eliminar(int IdentificadorComprobante) {
            return base.Channel.Eliminar(IdentificadorComprobante);
        }
        
        public System.Threading.Tasks.Task<SolucionSoap.Cliente.MVC.ServicioComprobante.EliminarRespuestaModelo> EliminarAsync(int IdentificadorComprobante) {
            return base.Channel.EliminarAsync(IdentificadorComprobante);
        }
        
        public SolucionSoap.Cliente.MVC.ServicioComprobante.ObtenerRespuestaModeloOfComprobanteModeloKTVAo3T5 Obtener(int IdentificadorComprobante) {
            return base.Channel.Obtener(IdentificadorComprobante);
        }
        
        public System.Threading.Tasks.Task<SolucionSoap.Cliente.MVC.ServicioComprobante.ObtenerRespuestaModeloOfComprobanteModeloKTVAo3T5> ObtenerAsync(int IdentificadorComprobante) {
            return base.Channel.ObtenerAsync(IdentificadorComprobante);
        }
        
        public SolucionSoap.Cliente.MVC.ServicioComprobante.ListarRespuestaModeloOfComprobanteModeloKTVAo3T5 Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<SolucionSoap.Cliente.MVC.ServicioComprobante.ListarRespuestaModeloOfComprobanteModeloKTVAo3T5> ListarAsync() {
            return base.Channel.ListarAsync();
        }
    }
}
